### ISSUE TITLE
rclone 1.66.0 stuck as "edge" channel?

### ISSUE THREAD

**Issue by johnandmegh** [boukendesho/rclone-snap#1]
Hi - it looks like rclone 1.66.0 is in the "edge" channel in the Snap store, even though it looked like it got picked up normally by the Action you have setup - is there something that anyone else could do to help with flipping that version number over to the "stable" snap channel?

Thanks!

**Comment by boukendesho** [comment]
Thank you for your reminder. 
The snap store can only manually publish stable versions. It has been updated now.：）

**Comment by johnandmegh** [comment]
```
$ rclone version
rclone v1.66.0
- os/version: ubuntu 23.10 (64 bit)
- os/kernel: 6.5.0-26-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.22.1
- go/linking: static
- go/tags: snap
```

Working great here, thanks!
